### PR TITLE
Ohos 1476 update api to work with an env file

### PR DESCRIPTION
**Pull request by AndrewBewseyTNA**
First round of updates to the go api and test file to incorporate env variables. 

FURTHER NOTE: apparently restart.sh mostly fixes itself if you walk away for 5 minutes. NOTE: consider, before merging - restart.sh doesn't work yet, but the rest seems to be. Is this better as a bug, considering the timing, or do you have suggestions on what I missed?

The other thing to consider -> do we want environmental variables for the error responses, or are we going to have nicer html pages for those in the future?

restart.sh ->
- This should work, but it doesn't. 
- Should shut down the entire setup, restart it in test mode, run the tests, then (based on the outcome) either restart in live mode, or display a message. 

in main.go -> 
1- env variables are gathered at startup
2 - functions are wrapped in echo's handlers, this lets you pass data to them 
3 - within the functions, where possible, hardcoded strings have been replaced with variables. 
4 - NOTE - the swagger/openapi docs tool doesn't let you have variables in the @route annotation, only hardcoded. I am attempting to sort this and will do a separate pr for that if successful. For now, endpoints have to be hardcoded. See -> https://github.com/swaggo/swag/issues/1470
5 - NOTE - with all the functions having been wrapped in handlers, everything has been shifted accross 1 tab, causing a lot of changes to show up. There are fewer changes than it looks like.  

in main_test.go -> 
1 - Harshads tests are incorporated, as I'd somehow branched from main before they were available. 
2 - The relevent env variables are gathered in each "phase" of testing, as this means we could run each phase separately. 
3 - As with main.go, where possible, hardcoding is replaced with an env variable. 

test.env -> 
- The intention is that live.env only ever lives on the ec2. 
- Currently, the only difference between live.env and test.env is that the welcome message is different
- I figure having this setup should help with the named graphs and switching between databases, but I'm not sure how. 

docker-compose -> 
- Minor tweak 

go.mod and go.sum -> 
- large changes as a result of "go mod tidy"

### CODE REVIEW

**Comment by AndrewBewseyTNA** [comment]
Minor correction to the restart script, and it works now.

**Comment by AndrewBewseyTNA** [comment]
Closed temporarily, Harshad made a good point re- docker and envs. 
Once I'm back, I'll correct the PR for that, then once its working as intended, re-open.

**Comment by AndrewBewseyTNA** [comment]
@mark-bell-tna @hgupta-tna PR re-opened and ammended. 

This now seems to be doing the trick; test and live env's are working, and restart.sh switches between the two. You switch environment by:
- stop all docker images
- set CURRENT_ENV
- re-setup docker compose (which picks up the correct env file to pass to the GoApi based on the CURRENT_ENV setting. 

As before, the @route annotation in the openapi generator doesn't work, this is going to be worked on next.

**Review by hgupta-tna — APPROVED** [review]

**Review by mark-bell-tna — CHANGES_REQUESTED** [review]
This looks fine with regard to the use of environment variables in the API. Looking at restart.sh it seems like it should be parameterised so that you pass the environment at the command line. As far as I can tell it repeats the same commands for TEST and LIVE, other than the test script. You could add an "if environment is TEST run the tests" bit at the end.
I'm also not clear about the purpose of the testing part but I've suggested to Harshad that it would be useful to have a full walkthrough of the whole system in the next few weeks, so we can save that until then.

**Comment by AndrewBewseyTNA** [comment]
Good point, and restart.sh now gathers the parameter, and decides whether or not to run tests based on it. 

@mark-bell-tna

**Review by mark-bell-tna — APPROVED** [review]
Thanks, Andrew. That looks better.

**Pull request merged**
